import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Logo from "./logo.svg"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <a
            href="/"
            target="_blank"
            rel="noopener noreferrer"
            className='logo-link'
          >
            <Logo />
          </a>
          <h1>
            Dashboard trader
          </h1>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
